[esp-wifi]
rx_queue_size = 15
tx_queue_size = 3
static_rx_buf_num = 10
dynamic_rx_buf_num = 24
ampdu_rx_enable = 0
ampdu_tx_enable = 0
rx_ba_win = 16
max_burst_size = 6
tick_rate_hz = 1000
country_code = "US"