[target.xtensa-esp32s3-none-elf]
runner = "espflash flash --flash-freq 80mhz --monitor -L defmt --partition-table partitions.csv --bootloader bootloader/bootloader.bin"
# runner = "probe-rs run --chip esp32s3 --idf-partition-table partitions.csv"

[env]
ESP_LOG = "INFO"
DEFMT_LOG = "info"
ESP_HAL_PLACE_SPI_DRIVER_IN_RAM = "true"
ESP_WIFI_TICK_RATE_HZ = "1000"
ESP_WIFI_AMPDU_TX_ENABLE = "false"
ESP_WIFI_AMPDU_RX_ENABLE = "false"
ESP_WIFI_TX_QUEUE_SIZE = "8"
ESP_WIFI_RX_QUEUE_SIZE = "10"
ESP_WIFI_STATIC_TX_BUF_NUM = "8"
ESP_WIFI_STATIC_RX_BUF_NUM = "8"
ESP_WIFI_DYNAMIC_RX_BUF_NUM = "10"
ESP_WIFI_DYNAMIC_TX_BUF_NUM = "10"
ESP_WIFI_RX_BA_WIN = "4"
ESP_WIFI_COUNTRY_CODE = "US"
ESP_WIFI_PHY_ENABLE_USB = "true"

[build]
rustflags = [
    "-Z",
    "stack-protector=strong",
    "-C",
    "link-arg=-Tlinkall.x",
    # "-C",
    # "link-arg=-Trom_functions.x",
    "-C",
    "link-arg=-nostartfiles",
    "-C",
    "link-arg=-Tdefmt.x",
]

target = "xtensa-esp32s3-none-elf"

[unstable]
build-std = ["alloc", "core"]
